name: Deploy to Dokploy
on:
  push:
    branches:
      - dev # Deploys every time you push to main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/yarn-install

      # Warm up Nx Cache (Using Nx Cloud)
      # This ensures the Docker build is nearly instant for steps that haven't changed.
      - name: Nx Build
        run: npx nx run-many -t build -p twenty-server twenty-front --parallel=3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & Push the production image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: packages/twenty-docker/twenty/Dockerfile
          target: twenty
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          # Passing Nx Cloud token into Docker allows even the Internal Docker build to stay cached
          build-args: |
            NX_CLOUD_ACCESS_TOKEN=${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      # Trigger your Dokploy instance to redeploy
      - name: Trigger Dokploy Webhook
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" \
               -H "Authorization: Bearer ${{ secrets.DOKPLOY_TOKEN }}"
